import process from 'node:process';
import { readFileSync, writeFileSync } from 'node:fs';
import { CHAT_ROOM_IDS } from '../src/features/chat/rooms.ts';

const path = 'supabase/functions/_shared/chatRoomIds.ts';
const content = `// Generated by pnpm generate:search-rooms. Edit src/features/chat/rooms.ts.\nexport const CHAT_ROOM_IDS = ${JSON.stringify(
  CHAT_ROOM_IDS.filter((id) => id !== 'all'),
  null,
  2
)} as const;\n`;
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== content) throw new Error('Run pnpm generate:search-rooms');
} else {
  writeFileSync(path, content);
}
